#!/usr/bin/env python3

def checkType(aChar):
  match (ord(aChar)):
    case 46 | 10:
      return 0
    case ascChar if 48 <= ascChar <= 57:
      return 1
    case 42:
      return 3
    case _:
      return 2

file1 = open('day3_2_input', 'r')
Lines = file1.readlines()
LineNr = 0
PartNr = ""
CurNr = ""
Gears=[]
GearResult={}
for Line in Lines:
  LineNr += 1
  CharNr = 0
  startLine = LineNr -1 if LineNr > 1  else 1
  endLine = LineNr + 1 if LineNr < len (Lines) else len (Lines)
  for char in Line:
    CharNr += 1
    match (checkType(char)):
      case 0 | 2 | 3:
        CurNr = ""
        if PartNr != "":
          uGears = [list(x) for x in set(tuple(x) for x in Gears)]
          for Gear in uGears:
            if str(Gear) not in GearResult:
              GearResult[str(Gear)]=[]
            GearResult[str(Gear)].append(PartNr)
          PartNr = ""
          Gears=[]
      case 1:
        CurNr += char
        startChar = CharNr -1 if CharNr > 1  else 1
        endChar = CharNr + 1
        for cLineNr in range (startLine - 1, endLine ):
          for cCharNr in range (startChar - 1, endChar ):
            if checkType (Lines[cLineNr][cCharNr]) == 3:
              PartNr = CurNr
              Gears.append([cLineNr,cCharNr])
        if PartNr != "":
          PartNr = CurNr 
TotalGeared=0
for GearedParts in GearResult.values():
  if len(GearedParts) == 2:
    TotalGeared += int(GearedParts[0]) * int(GearedParts[1])
print (TotalGeared)
