#!/usr/bin/env python3
import numpy as np

file1 = open('day4_1_input', 'r')
Lines = file1.readlines()
scratchcards=np.ones(len(Lines))
lineNr=0
for Line in Lines:
  splitLine = Line.split()
  sepIndex = splitLine.index("|")
  winningNum = splitLine[1:sepIndex]
  myNum = splitLine [sepIndex + 1:]
  numMatch = len(set(winningNum).intersection(myNum))
  if numMatch:
    scratchcards[lineNr+1:lineNr+numMatch+1] += scratchcards[lineNr]
  lineNr += 1
print (scratchcards.sum())
