#!/usr/bin/env python3

file1 = open('day4_1_input', 'r')
Lines = file1.readlines()
Winnings = 0
for Line in Lines:
  splitLine = Line.split()
  sepIndex = splitLine.index("|")
  winningNum = splitLine[1:sepIndex]
  myNum = splitLine [sepIndex + 1:]
  numMatch = len(set(winningNum).intersection(myNum))
  if numMatch:
    Winnings += pow(2, numMatch -1)
print (Winnings)
