#!/usr/bin/awk -f

     {
     	n = ($1 == "noop") ? 1 : 2
     	for (i = 1; i <= n; i++) {
     		d = (x-c < 1) && (x-c > -3) ? "#" : "."
     		r = r d
     		++c
		if ( c == 40){
			print r
			r = ""
			c = 0
			}
		}
     	x += $2
	}
