#!/usr/bin/awk -f

	# BEGIN regel(s)

	BEGIN {
	t=9
	for (i=0;i<=t;++i)
		{
		sr[i]=0
       		sc[i]=0
		}
       	s[sr[t] "," sc[t]] = 1
	}

	# Regel(s)

    {
   	for (j = $2; j > 0; --j) {
   		if ($1 == "D") { 
    			++sr[0]
			}
  		if ($1 == "U") { 
    			--sr[0]
			}
   		if ($1 == "R") {
    			++sc[0]
			}
  		if ($1 == "L") {
  			--sc[0]
			}
		for (i=1;i<=t;++i){
  			if (((sr[i-1] - sr[i]) ^ 2) + ((sc[i-1] - sc[i]) ^ 2) == 8) {
				sr[i] = (sr[i] + sr[i-1])/2
				sc[i] = (sc[i] + sc[i-1])/2
			}
  			else if (((sr[i-1] - sr[i]) ^ 2) == 4) {
				if (sc[i-1] == sc[i]) {
					sr[i] = (sr[i] + sr[i-1])/2
				}
				else {
					sr[i] = (sr[i] + sr[i-1])/2
					sc[i] = sc[i-1]
				}
			}
			else if (((sc[i-1] - sc[i]) ^ 2) == 4) {
				if (sr[i-1] == sr[i]) {
					sc[i] = (sc[i] + sc[i-1])/2
				}
                                else {
                                        sc[i] = (sc[i] + sc[i-1])/2
                                        sr[i] = sr[i-1]
				}
			}
			else break
			}
       		s[sr[t] "," sc[t]] = 1
		}
	}

	# END regel(s)

	END {
       	print length(s)
	}

